language: clojure
lein: 2.7.1
script:
  - lein cljfmt check
  - lein test
sudo: required
jdk:
  - openjdk8

after_success:
  - CLOVERAGE_VERSION=1.1.2 lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: change