name: test

on: [push]

jobs:
  clojure:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          lein: 2.9.5

      - name: Test
        run: |
          lein cljfmt check
          lein test
        shell: bash

      - name: Run codecov
        run: |
          lein cloverage --codecov
          bash <(curl -s https://codecov.io/bash)
        shell: bash
